"""
Tests for :mod:`src.mathcore.numbertheory.primality`.

The roadmap's exit gate for this module is that BPSW agrees with a reference
sieve on every integer below a bound with no disagreement. A sieve is an
independent oracle in the way a second probable-prime test would not be: it
decides primality by construction rather than by a congruence, so agreement is
evidence rather than a shared assumption.

The Lucas sequences are checked against the Fibonacci and Lucas numbers
generated by the naive recurrence, which is the definition the fast doubling
ladder is an optimisation of.
"""

from __future__ import annotations

import pytest

from src.mathcore.numbertheory.primality import (
    SMALL_PRIMES,
    is_probable_prime,
    lucas_sequence,
    selfridge_parameters,
    strong_lucas_probable_prime,
    strong_probable_prime,
)

SIEVE_LIMIT = 100_000

# Carmichael numbers: composites that pass a Fermat test to every coprime base,
# which is exactly what a strong test and a Lucas test are there to catch.
CARMICHAELS = (561, 1105, 1729, 2465, 2821, 6601, 8911, 41041, 62745, 162401)

# Composites that are strong probable primes to base 2 -- the first half of
# BPSW passes these, so they exercise the second half and nothing else.
SPSP_BASE_2 = (2047, 3277, 4033, 4681, 8321, 15841, 29341, 42799, 49141, 52633)

# Strong Lucas pseudoprimes for Selfridge's Method A parameters -- the second
# half of BPSW passes these. That they are disjoint from SPSP_BASE_2 is the
# whole reason the pair is used together, and the tests below assert it.
LUCAS_PSEUDOPRIMES = (5459, 5777, 10877, 16109, 18971)

# Perfect squares of primes, which make the Selfridge parameter scan
# non-terminating unless they are screened first.
PRIME_SQUARES = (9, 25, 49, 121, 169, 1_000_003**2)

BIG_PRIMES = (
    (1 << 61) - 1,
    (1 << 89) - 1,
    (1 << 255) - 19,
    (1 << 256) - (1 << 32) - 977,
    2**521 - 1,
)


@pytest.fixture(scope="module")
def sieve() -> list[bool]:
    """Sieve of Eratosthenes up to :data:`SIEVE_LIMIT`, inclusive."""
    flags = [True] * (SIEVE_LIMIT + 1)
    flags[0] = flags[1] = False
    for i in range(2, int(SIEVE_LIMIT**0.5) + 1):
        if flags[i]:
            flags[i * i :: i] = [False] * len(flags[i * i :: i])
    return flags


# ---- the exit gate ---------------------------------------------------------


def test_bpsw_agrees_with_the_sieve_on_every_integer_below_the_limit(
    sieve: list[bool],
) -> None:
    disagreements = [n for n in range(SIEVE_LIMIT + 1) if is_probable_prime(n) != sieve[n]]
    assert disagreements == []


def test_negative_and_trivial_values_are_not_prime() -> None:
    for n in (-7, -1, 0, 1):
        assert not is_probable_prime(n)


def test_two_is_prime() -> None:
    assert is_probable_prime(2)


@pytest.mark.parametrize("n", CARMICHAELS)
def test_carmichael_numbers_are_rejected(n: int) -> None:
    assert not is_probable_prime(n)


@pytest.mark.parametrize("n", SPSP_BASE_2)
def test_base_2_strong_pseudoprimes_are_caught_by_the_lucas_half(n: int) -> None:
    assert strong_probable_prime(n, 2), "this fixture must pass the first half"
    assert not strong_lucas_probable_prime(n), "the second half must catch it"
    assert not is_probable_prime(n)


@pytest.mark.parametrize("n", PRIME_SQUARES)
def test_perfect_squares_terminate_and_are_rejected(n: int) -> None:
    """Without the square screen the Selfridge scan would not terminate."""
    assert not strong_lucas_probable_prime(n)
    assert not is_probable_prime(n)


@pytest.mark.parametrize("n", BIG_PRIMES)
def test_large_known_primes_are_accepted(n: int) -> None:
    assert is_probable_prime(n)


@pytest.mark.parametrize("n", BIG_PRIMES)
def test_the_square_of_a_large_prime_is_rejected(n: int) -> None:
    """A prime square has no small factor, so only the square screen catches it."""
    assert not is_probable_prime(n * n)


def test_products_of_two_large_primes_are_rejected() -> None:
    p = (1 << 127) - 1
    q = (1 << 89) - 1
    assert not is_probable_prime(p * q)


def test_non_integer_input_is_rejected() -> None:
    with pytest.raises(TypeError):
        is_probable_prime(True)
    with pytest.raises(TypeError):
        is_probable_prime(7.0)  # type: ignore[arg-type]


def test_small_primes_table_is_correct_and_sorted(sieve: list[bool]) -> None:
    assert list(SMALL_PRIMES) == sorted(SMALL_PRIMES)
    assert all(sieve[p] for p in SMALL_PRIMES)
    assert [n for n in range(2, 256) if sieve[n]] == list(SMALL_PRIMES)


# ---- the Miller-Rabin half -------------------------------------------------


def test_strong_probable_prime_agrees_with_the_sieve_on_a_prefix(
    sieve: list[bool],
) -> None:
    """
    Below 2047 no odd composite is a strong probable prime to base 2, so the
    base-2 test alone is exact there -- a sharp statement the sieve can check.
    """
    for n in range(5, 2047, 2):
        assert strong_probable_prime(n, 2) == sieve[n], n


@pytest.mark.parametrize("n", LUCAS_PSEUDOPRIMES)
def test_lucas_pseudoprimes_are_caught_by_the_base_2_half(n: int) -> None:
    """The mirror image of the SPSP fixtures: here the second half is fooled."""
    assert strong_lucas_probable_prime(n), "this fixture must pass the second half"
    assert not strong_probable_prime(n, 2), "the first half must catch it"
    assert not is_probable_prime(n)


def test_the_two_halves_fail_on_disjoint_sets() -> None:
    """
    The claim BPSW rests on, stated as an assertion rather than a comment.
    Neither fixture set overlaps the other, so no number here passes both.
    """
    assert not set(SPSP_BASE_2) & set(LUCAS_PSEUDOPRIMES)


@pytest.mark.parametrize("base", [0, 1, -1, 2048, 2046])
def test_trivial_bases_are_refused_rather_than_answered(base: int) -> None:
    """0 and +-1 satisfy the congruence for every n; a True from them is empty."""
    with pytest.raises(ValueError, match="trivial"):
        strong_probable_prime(2047, base)


@pytest.mark.parametrize("bad", [0, 1, 2, -3])
def test_strong_probable_prime_rejects_a_modulus_below_three(bad: int) -> None:
    with pytest.raises(ValueError):
        strong_probable_prime(bad, 2)


def test_strong_probable_prime_rejects_an_even_modulus() -> None:
    with pytest.raises(ValueError, match="odd"):
        strong_probable_prime(1 << 20, 3)


def test_strong_probable_prime_rejects_a_non_integer_modulus() -> None:
    with pytest.raises(TypeError):
        strong_probable_prime(True, 2)


# ---- Lucas sequences -------------------------------------------------------


def _naive_lucas(n: int, p: int, q: int, k: int) -> tuple[int, int, int]:
    """``(U_k, V_k, q**k) mod n`` straight from the defining recurrence."""
    u0, u1 = 0, 1
    v0, v1 = 2, p % n
    for _ in range(k):
        u0, u1 = u1, (p * u1 - q * u0) % n
        v0, v1 = v1, (p * v1 - q * v0) % n
    return u0 % n, v0 % n, pow(q, k, n)


@pytest.mark.parametrize("params", [(1, -1), (1, 2), (3, 5), (5, -3), (7, 11)])
def test_the_ladder_matches_the_recurrence(params: tuple[int, int]) -> None:
    p, q = params
    for n in (3, 7, 97, 1009, 65537):
        for k in range(0, 60):
            assert lucas_sequence(n, p, q, k) == _naive_lucas(n, p, q, k), (n, p, q, k)


def test_p_one_q_minus_one_gives_the_fibonacci_and_lucas_numbers() -> None:
    """The registry entry names this family; here it is, explicitly."""
    fib = [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]
    luc = [2, 1, 3, 4, 7, 11, 18, 29, 47, 76, 123, 199, 322, 521, 843]
    modulus = 10**9 + 7
    for k, (f, lucas_k) in enumerate(zip(fib, luc, strict=True)):
        u, v, _ = lucas_sequence(modulus, 1, -1, k)
        assert u == f, k
        assert v == lucas_k, k


def test_the_ladder_handles_an_index_far_past_any_naive_loop() -> None:
    """Logarithmic cost is the point; a linear implementation could not run this."""
    n = (1 << 255) - 19
    u, v, qk = lucas_sequence(n, 1, -1, n + 1)
    assert 0 <= u < n and 0 <= v < n and 0 <= qk < n


def test_lucas_sequence_rejects_a_negative_index() -> None:
    with pytest.raises(ValueError, match="k >= 0"):
        lucas_sequence(7, 1, -1, -1)


@pytest.mark.parametrize("bad", [0, 1, 2, 8, -3])
def test_lucas_sequence_rejects_a_non_odd_modulus(bad: int) -> None:
    """Halving is exact only modulo an odd n."""
    with pytest.raises(ValueError):
        lucas_sequence(bad, 1, -1, 5)


# ---- Selfridge parameters --------------------------------------------------


def test_selfridge_finds_a_jacobi_minus_one_discriminant(sieve: list[bool]) -> None:
    from src.mathcore.numbertheory.residues import jacobi_symbol

    for n in range(5, 5000, 2):
        if not sieve[n]:
            continue
        d, p, q = selfridge_parameters(n)
        assert p == 1, n
        assert jacobi_symbol(d, n) == -1, n
        assert d == p * p - 4 * q, n


def test_selfridge_reports_a_shared_factor_as_a_composite_sentinel() -> None:
    """``(5/n) == 0`` for a multiple of 5 -- a proof, not a probable answer."""
    d, p, q = selfridge_parameters(15)
    assert (d, p, q) == (5, 0, 0)


def test_selfridge_does_not_mistake_n_itself_for_a_shared_factor() -> None:
    """``(5/5) == 0``, but 5 is prime; the scan must continue past it."""
    d, p, _q = selfridge_parameters(5)
    assert p == 1
    assert d == -7


@pytest.mark.parametrize("bad", [0, 1, 2, 8, -3])
def test_selfridge_rejects_a_non_odd_modulus(bad: int) -> None:
    with pytest.raises(ValueError):
        selfridge_parameters(bad)


# ---- the Lucas half --------------------------------------------------------


def test_strong_lucas_agrees_with_the_sieve_below_its_first_pseudoprime(
    sieve: list[bool],
) -> None:
    """
    5459 is the least strong Lucas pseudoprime for these parameters, so below
    it the second half is exact -- and the bound is asserted, not assumed: the
    loop stops exactly where :data:`LUCAS_PSEUDOPRIMES` begins.
    """
    assert LUCAS_PSEUDOPRIMES[0] == 5459
    for n in range(3, LUCAS_PSEUDOPRIMES[0], 2):
        assert strong_lucas_probable_prime(n) == sieve[n], n


@pytest.mark.parametrize("bad", [0, 1, 2, 8, -3])
def test_strong_lucas_rejects_a_non_odd_modulus(bad: int) -> None:
    with pytest.raises(ValueError):
        strong_lucas_probable_prime(bad)
