"""
Install, upgrade and remove the host pieces of the terminal service.

Two files, both owned by this module and both marked as such:

* ``~/.local/bin/tradebot-term`` -- a wrapper that runs this checkout's
  interpreter, so the CLI works without activating the virtualenv;
* ``$XDG_CONFIG_HOME/systemd/user/tradebot-terminal.service`` -- a user unit
  (when ``systemctl --user`` works) that keeps the daemon running and empties
  its cgroup on stop (``KillMode=mixed``), so no session process outlives it.

Re-running the installer is the upgrade: a marked file is rewritten in place.
A file at either path *without* the marker is somebody else's and is never
overwritten or removed -- the install reports the conflict and fails instead.
Nothing here reads, writes or rotates the access token, and nothing touches
the trading .env.

Registry: TERM-008 (config/quality_registry.json).
"""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
from collections.abc import Callable, Mapping
from dataclasses import dataclass, field
from pathlib import Path

MARKER = "managed-by: tradebot-terminal"
UNIT_NAME = "tradebot-terminal.service"

Runner = Callable[[list[str]], int]


def run_quietly(argv: list[str]) -> int:
    """Run a host command for its exit status only; a missing binary is 127."""
    try:
        completed = subprocess.run(
            argv,
            check=False,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=30,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return 127
    return completed.returncode


@dataclass
class InstallReport:
    written: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)
    conflicts: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.conflicts


def bin_dir(env: Mapping[str, str]) -> Path:
    return Path(env.get("HOME", str(Path.home()))) / ".local" / "bin"


def unit_dir(env: Mapping[str, str]) -> Path:
    config_home = env.get("XDG_CONFIG_HOME", "").strip()
    base = Path(config_home) if config_home else Path(env.get("HOME", str(Path.home()))) / ".config"
    return base / "systemd" / "user"


def wrapper_text(python: Path, repo: Path) -> str:
    return (
        "#!/bin/sh\n"
        f"# {MARKER}\n"
        "# Host CLI for the Trade-Bot terminal service; regenerated by `tradebot-term install`.\n"
        f"PYTHONPATH={shlex.quote(str(repo))}${{PYTHONPATH:+:$PYTHONPATH}}\n"
        "export PYTHONPATH\n"
        # -P: without it `python -m` puts the caller's working directory first
        # on sys.path, and any directory holding its own `src` package (another
        # checkout, another project) would be imported instead of this one.
        f'exec {shlex.quote(str(python))} -P -m src.terminal "$@"\n'
    )


def _systemd_quote(value: str, *, command: bool) -> str:
    """
    Double-quote one unit-file value.

    Specifiers (%) are expanded everywhere; $VARIABLE only on command lines,
    so ``$`` is doubled only there.
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("%", "%%")
    if command:
        escaped = escaped.replace("$", "$$")
    return f'"{escaped}"'


def unit_text(python: Path, repo: Path) -> str:
    # `sh -l` gives the daemon -- and so every shell it starts -- the user's
    # login environment (PATH from ~/.profile), not systemd's minimal one.
    # `$$1` is systemd's spelling of a literal `$1`.
    script = 'exec "$$1" -P -m src.terminal daemon'
    return (
        f"# {MARKER}\n"
        "[Unit]\n"
        "Description=Trade-Bot integrated terminal and process service\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        f"WorkingDirectory={str(repo).replace('%', '%%')}\n"
        f"Environment={_systemd_quote('PYTHONPATH=' + str(repo), command=False)}\n"
        f"ExecStart=/bin/sh -lc '{script}' tradebot-terminal "
        f"{_systemd_quote(str(python), command=True)}\n"
        "Restart=on-failure\n"
        "RestartSec=2s\n"
        "KillMode=mixed\n"
        "TimeoutStopSec=15s\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def _write_managed(path: Path, text: str, mode: int, report: InstallReport) -> bool:
    """Write *text* unless an unmanaged file is in the way. True if written."""
    if path.exists() or path.is_symlink():
        try:
            current = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            current = ""
        if MARKER not in current:
            report.conflicts.append(f"{path} exists and was not created by this installer")
            return False
        if current == text:
            report.unchanged.append(str(path))
            os.chmod(path, mode)
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + ".tmp")
    temporary.write_text(text, encoding="utf-8")
    os.chmod(temporary, mode)
    os.replace(temporary, path)
    report.written.append(str(path))
    return True


def systemd_user_available(run: Runner) -> bool:
    if shutil.which("systemctl") is None:
        return False
    return run(["systemctl", "--user", "show-environment"]) == 0


def install(
    *,
    python: Path,
    repo: Path,
    env: Mapping[str, str],
    use_systemd: bool = True,
    run: Runner = run_quietly,
) -> InstallReport:
    report = InstallReport()
    _write_managed(bin_dir(env) / "tradebot-term", wrapper_text(python, repo), 0o755, report)
    if not use_systemd:
        report.notes.append("systemd unit skipped (--no-systemd)")
        return report
    if not systemd_user_available(run):
        report.notes.append(
            "systemctl --user is not available; the dashboard starts the daemon on demand"
        )
        return report
    unit_path = unit_dir(env) / UNIT_NAME
    changed = _write_managed(unit_path, unit_text(python, repo), 0o644, report)
    if is_managed(unit_path):
        run(["systemctl", "--user", "daemon-reload"])
        if run(["systemctl", "--user", "enable", "--now", UNIT_NAME]) != 0:
            report.notes.append(f"could not enable {UNIT_NAME}; see `systemctl --user status`")
        elif changed:
            report.notes.append(
                "unit updated; the running daemon keeps its sessions until `tradebot-term restart`"
            )
    return report


def uninstall(
    *,
    env: Mapping[str, str],
    state_dir: Path,
    purge: bool = False,
    run: Runner = run_quietly,
) -> InstallReport:
    report = InstallReport()
    unit_path = unit_dir(env) / UNIT_NAME
    if is_managed(unit_path):
        run(["systemctl", "--user", "disable", "--now", UNIT_NAME])
        unit_path.unlink()
        run(["systemctl", "--user", "daemon-reload"])
        report.removed.append(str(unit_path))
    elif unit_path.exists():
        report.conflicts.append(f"{unit_path} was not created by this installer; left in place")
    wrapper = bin_dir(env) / "tradebot-term"
    if is_managed(wrapper):
        wrapper.unlink()
        report.removed.append(str(wrapper))
    elif wrapper.exists():
        report.conflicts.append(f"{wrapper} was not created by this installer; left in place")
    if purge and state_dir.is_dir():
        shutil.rmtree(state_dir)
        report.removed.append(str(state_dir))
    return report


def is_managed(path: Path) -> bool:
    try:
        return path.is_file() and MARKER in path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False
