"""
Safe primes, prime-order subgroups, and small-subgroup confinement.

Owns the ``safe-primes-dh`` registry entry.

A Diffie-Hellman group modulo ``p`` has subgroups of every order dividing
``p - 1``. If ``p - 1`` has small factors, an attacker can send a public value
of small order and confine the shared secret to that subgroup's handful of
elements -- then try all of them. Choosing ``p = 2q + 1`` with ``q`` prime
removes the choice: ``p - 1 = 2q`` factors as ``2 * q`` and nothing else, so the
only subgroup orders are 1, 2, ``q`` and ``p - 1``. The orders 1 and 2 are
generated by exactly ``{1}`` and ``{1, p - 1}``, which is why a validated
implementation rejects those two public values by name and is then done.

That is the whole of the defence, and it has two halves that are easy to
separate by accident:

1. **The parameters are a safe-prime group.** :func:`is_safe_prime` and
   :func:`validate_group`.
2. **Every received public value lies in the prime-order subgroup.**
   :func:`is_valid_public_value`. Skipping this is the actual attack: correct
   parameters do not stop a peer from *sending* an element of order 2.

**No named group's modulus is hardcoded here.** RFC 7919 fixes several, and
copying a 2048-bit constant from memory into a file is how this project has
shipped a fabricated constant three times. Instead the caller supplies the
modulus and these functions verify its structure, which is strictly stronger:
a transcription error in a modulus obtained anywhere is caught by
:func:`validate_group` rather than trusted.

**Not constant time**, and deliberately not a DH implementation. There is no
key agreement, no exponentiation of a secret and no random source here -- only
predicates over public parameters, so there is nothing for a timing adversary
to recover. A real implementation must also perform the exponentiation in
constant time, which is not this module's job.

References: RFC 7919 (named finite-field DH groups); RFC 2785; Lim-Lee,
"A key recovery attack on discrete log based schemes using a prime order
subgroup" (1997); Valenta et al., "Measuring small subgroup attacks against
Diffie-Hellman" (2017).

Registry: SECR-015, SECR-016 (config/quality_registry.json).
"""

from __future__ import annotations

from dataclasses import dataclass

from src.mathcore.numbertheory.primality import is_probable_prime

# Public values whose order is 1 or 2. In a safe-prime group these are the
# *only* elements outside the prime-order subgroup, so naming them is a
# complete enumeration rather than a heuristic -- which is exactly what the
# safe-prime structure buys.
#
# 0 is not a group element at all; 1 has order 1; p - 1 has order 2. A peer
# sending any of them confines the shared secret to one or two values.
_TRIVIAL_ORDERS = (0, 1)


class SafePrimeError(ValueError):
    """
    A parameter or value check that must not be allowed to return a verdict.

    Distinct from returning False: False is "these parameters are not a safe
    prime group", an answer. This is "the question was malformed" -- a modulus
    of 4, a negative exponent -- where answering either way would be a guess.
    """


@dataclass(frozen=True)
class GroupVerdict:
    """
    The outcome of validating a candidate Diffie-Hellman group.

    Carries the reasons rather than only a bool, because "these parameters are
    unsafe" is not actionable and "p is prime but (p-1)/2 is composite" is:
    it says the modulus is a prime that is not a *safe* prime, which is a
    different mistake from a composite modulus and has a different fix.
    """

    ok: bool
    subgroup_order: int | None
    problems: tuple[str, ...]

    def __bool__(self) -> bool:
        return self.ok


def subgroup_order(p: int) -> int:
    """
    The prime-order subgroup's order ``q = (p - 1) / 2`` for a safe prime ``p``.

    Raises if ``p`` is even, since ``(p - 1) / 2`` is then not an integer and a
    silently floored value would be a different group's order.
    """
    if p < 5:
        raise SafePrimeError(f"a safe prime is at least 5, got {p}")
    if p % 2 == 0:
        raise SafePrimeError(f"p must be odd for (p-1)/2 to be an integer, got {p}")
    return (p - 1) // 2


def is_sophie_germain_prime(q: int) -> bool:
    """Whether ``q`` and ``2q + 1`` are both prime, making ``2q + 1`` safe."""
    if q < 2:
        return False
    return is_probable_prime(q) and is_probable_prime(2 * q + 1)


def is_safe_prime(p: int) -> bool:
    """
    Whether ``p`` is prime and ``(p - 1) / 2`` is prime.

    Both halves are required and the second is the one that gets dropped. A
    prime modulus alone says nothing about the subgroup structure: ``p - 1``
    can still be smooth, which is precisely the condition a small-subgroup
    attack needs.
    """
    if p < 5 or p % 2 == 0:
        return False
    if not is_probable_prime(p):
        return False
    return is_probable_prime((p - 1) // 2)


def validate_group(p: int, g: int) -> GroupVerdict:
    """
    Check that ``(p, g)`` is a safe-prime group with a generator of order ``q``.

    Reports every problem it finds rather than the first, so an operator fixing
    parameters learns the whole story in one pass instead of one problem per
    attempt.

    The generator check is ``g^q == 1 mod p`` with ``g`` not trivial: that is
    what places ``g`` in the prime-order subgroup rather than merely in the
    group. A ``g`` of order ``2q`` is not itself an attack -- the classic
    choice ``g = 2`` often has full order -- but a ``g`` of order 2 is, and
    generating in the prime-order subgroup is what makes
    :func:`is_valid_public_value` a complete check on the other side.
    """
    problems: list[str] = []

    if p < 5:
        raise SafePrimeError(f"a candidate modulus must be at least 5, got {p}")
    if p % 2 == 0:
        return GroupVerdict(False, None, (f"p is even ({p}); a DH modulus must be an odd prime",))

    q = (p - 1) // 2
    p_prime = is_probable_prime(p)
    q_prime = is_probable_prime(q)

    if not p_prime:
        problems.append("p is composite")
    if not q_prime:
        problems.append(
            "(p-1)/2 is composite, so p is not a safe prime: p-1 has factors "
            "beyond 2q and the group contains small subgroups an attacker can "
            "confine the shared secret to"
        )

    if not 1 < g < p - 1:
        problems.append(
            f"g={g} is outside 1 < g < p-1; the excluded values have order 1 "
            "or 2 and generate one or two elements"
        )
    elif p_prime and q_prime and pow(g, q, p) != 1:
        problems.append(
            f"g={g} is not in the prime-order subgroup (g^q != 1 mod p), so "
            "public values derived from it need a stronger membership check "
            "than the subgroup test provides"
        )

    return GroupVerdict(not problems, q if p_prime and q_prime else None, tuple(problems))


def is_valid_public_value(y: int, p: int) -> bool:
    """
    Whether a received public value lies in the prime-order subgroup of ``p``.

    **This is the check that actually stops the attack.** Correct parameters do
    not prevent a peer from sending an element of small order -- validating the
    group proves what subgroups exist, not what the other side transmitted. A
    deployment with a perfect RFC 7919 modulus and no value check is still
    vulnerable, and that combination is what Valenta et al. found in the field.

    Assumes ``p`` is a safe prime, which is what makes the test complete: the
    only orders are 1, 2, ``q`` and ``2q``, so excluding ``y <= 1`` and
    ``y >= p - 1`` removes every element of order 1 or 2 and the exponentiation
    confirms the rest. Under a non-safe ``p`` the same code is a partial check,
    so :func:`validate_group` is not optional.
    """
    if p < 5 or p % 2 == 0:
        raise SafePrimeError(f"p must be an odd prime of at least 5, got {p}")
    if y in _TRIVIAL_ORDERS or y >= p - 1:
        return False
    return pow(y, (p - 1) // 2, p) == 1


def order_of(y: int, p: int) -> int | None:
    """
    The multiplicative order of ``y`` mod a safe prime ``p``, or None if ``y``
    is not a unit.

    Only the four possible orders are tried -- 1, 2, ``q``, ``2q`` -- because in
    a safe-prime group there are no others. That is the point of the structure,
    and it makes this exact rather than a search: a generic order-finding
    routine over a 2048-bit group would not terminate usefully.

    ``p`` is therefore *verified* safe before the four candidates are tried,
    not assumed. Under a non-safe ``p`` the smallest candidate that satisfies
    ``y^k == 1`` need not be the order at all -- for ``p = 13``, ``y = 3`` has
    order 3, which is not in ``(1, 2, 6, 12)``, and the loop would return 6.
    That is a wrong answer shaped exactly like a right one, so the assumption
    is checked instead of documented.

    Exists so a rejection is explicable. "Your public value has order 2" tells
    a peer what they did; "invalid public value" invites them to retry with the
    same bytes.
    """
    if p < 5 or p % 2 == 0:
        raise SafePrimeError(f"p must be an odd prime of at least 5, got {p}")
    if not is_safe_prime(p):
        raise SafePrimeError(
            f"p={p} is not a safe prime, so the orders are not confined to "
            "(1, 2, q, 2q) and the smallest candidate satisfying y^k == 1 need "
            "not be the order. Refusing rather than returning a multiple of it."
        )

    y %= p
    if y == 0:
        return None

    q = (p - 1) // 2
    for candidate in (1, 2, q, 2 * q):
        if pow(y, candidate, p) == 1:
            return candidate
    # Unreachable: p is a verified safe prime, every unit's order divides 2q,
    # and 2q's divisors are exactly the four tried above.
    raise AssertionError(  # pragma: no cover - unreachable for a safe prime
        f"no order among (1, 2, q, 2q) for y={y} mod safe prime {p}"
    )


def smallest_factor_of_p_minus_one(p: int, bound: int = 1 << 16) -> int | None:
    """
    The smallest odd factor of ``p - 1`` below ``bound``, or None if there is none.

    A diagnostic for why a modulus is unsafe, and the quantity an attacker
    actually wants: a small odd factor ``r`` of ``p - 1`` is a subgroup of
    order ``r`` to confine a secret into. Trial division, bounded, because the
    useful answer is "there is a small factor" and finding a large one is a
    factoring problem rather than a check.

    Returns None for a safe prime, since ``p - 1 = 2q`` has no odd factor below
    the bound except ``q`` itself when ``q`` is tiny.
    """
    if p < 5:
        raise SafePrimeError(f"a candidate modulus must be at least 5, got {p}")
    if bound < 3:
        raise SafePrimeError(f"bound must be at least 3, got {bound}")

    n = p - 1
    while n % 2 == 0:
        n //= 2  # the factor 2 is expected and is handled by the value check

    factor = 3
    while factor < bound and factor * factor <= n:
        if n % factor == 0:
            return factor
        factor += 2
    return n if 1 < n < bound else None
